package com.desafio.apilocalizacao.ApiLocalizacao.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.desafio.apilocalizacao.ApiLocalizacao.util.LocalDateConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.joda.time.DateTime;

import java.time.LocalDate;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "solicitacao_cep")
public class SolicitacaoCepDTO {
    private String identificador;
    private String cep;
    private String status;
    private LocalDate dataSolicitacao;
    @DynamoDBVersionAttribute
    private Long version; // O campo deve ser do tipo Long

    @DynamoDBAutoGeneratedKey
    public String getIdentificador() {
        return identificador;
    }

    @DynamoDBHashKey
    public String getCep() {
        return cep;
    }

    @DynamoDBTypeConverted(converter = LocalDateConverter.class)  // Usando o conversor para LocalDate
    @DynamoDBAttribute(attributeName = "dataSolicitacao")
    public LocalDate getDataSolicitacao() {
        return dataSolicitacao;
    }
}
